kernel: mm: uksm: Fix missing qualifiers
Test compiler: clang-android-9

kernel/nubia/sm8150/mm/uksm.c:174:17: error: initializing 'unsigned long *' with an
expression of type 'const void *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        unsigned long *src = s1;
                       ^     ~~
  CC      drivers/hid/hid-apple.o
  AS      arch/arm64/kernel/head.o

Signed-off-by: gesangtome <gesangtome@foxmail.com>
Change-Id: I1b994cf0e4b78fe8331b184de267b9294ac7b5c8